version: '3'

services:
  spring-app:
    image: ghcr.io/peageon/ssock:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/test_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - backend
  postgres-db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
#  postgres-db:
#    image: postgres:latest
#    environment:
#      POSTGRES_DB: test_db
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: 1234
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#    networks:
#      - backend

networks:
  backend:
volumes:
  postgres-data:
